version: 2

models:
    - name: customers
      description: the customer table
      docs:
        show: true
      columns: 
       - name: customer_id
         tests:
           - unique
           - not_null